sot/skare3

- ska_conda/ska_builder.py
Use old conda build strings and skip the build hashes
> Use old conda build strings and skip the build hashes

- ska_conda/pkg_defs/ska3-core/meta.yaml
- ska_conda/pkg_defs/ska3-dev/meta.yaml
- ska_conda/pkg_defs/ska3-flight/meta.yaml
- ska_conda/pkg_defs/ska3-pinned/meta.yaml
- ska_conda/pkg_defs/ska3-template/meta.yaml
- ska_conda/pkg_defs/ska3_builder/meta.yaml
Build the ska3* packages as noarch
> Build the ska3* packages as noarch

- setup.py
- ska_conda/pkg_defs/Chandra.Maneuver/meta.yaml
- ska_conda/pkg_defs/annie/meta.yaml
- ska_conda/pkg_defs/maude/meta.yaml
- ska_conda/pkg_defs/parse_cm/meta.yaml
- ska_conda/pkg_defs/ska3_builder/meta.yaml
- ska_conda/ska_builder.py
This PR removes the logic that tries to git clone packages using ssh by default, and instead just explicitly uses whatever string is after "home:" in the meta.yaml.  For private packages, that is now set to the github ssh string.  For the rest, it is set to the https url.
Closes #8 (via explicit compromise on https and ssh urls)
> Simplify git cloning

- ska_conda/pkg_defs/ska3-core/combine_arch.py
- ska_conda/pkg_defs/ska3-core/meta.yaml
- ska_conda/pkg_defs/ska3-dev/meta.yaml
- ska_conda/pkg_defs/ska3-flight/meta.yaml
- ska_conda/pkg_defs/ska3-pinned/meta.yaml
- ska_conda/pkg_defs/ska3_builder/meta.yaml
Configure the ska3-core metapackage recipe to have arch-specific dependencies as needed.
Closes #36 
Closes #24 
Closes #42
> ska3-core with arch-specific packages

- ska_conda/build_order.txt
- ska_conda/pkg_defs/astropy/RECIPE_LICENSE
- ska_conda/pkg_defs/astropy/bld.bat
- ska_conda/pkg_defs/astropy/build.sh
- ska_conda/pkg_defs/astropy/meta.yaml
- ska_conda/pkg_defs/astropy/run_test.py
- ska_conda/pkg_defs/pytest-arraydiff/meta.yaml
- ska_conda/pkg_defs/pytest-astropy/meta.yaml
- ska_conda/pkg_defs/pytest-doctestplus/meta.yaml
- ska_conda/pkg_defs/pytest-openfiles/meta.yaml
- ska_conda/pkg_defs/pytest-remotedata/meta.yaml
- ska_conda/ska_builder.py
Bundle a recipe for astropy (and some test dependencies) in skare3 to give us an astropy 3.0.3 that will still run on our CentOS5-compatible Linux env.
> Add local astropy

- ska_conda/pkg_defs/ska3-template/bin/flt_envs
- ska_conda/pkg_defs/ska3-template/bin/ska_envs.csh
- ska_conda/pkg_defs/ska3-template/bin/ska_envs.sh
- ska_conda/pkg_defs/ska3-template/bin/ska_version
- ska_conda/pkg_defs/ska3-template/build.sh
- ska_conda/pkg_defs/ska3-template/meta.yaml
- ska_conda/pkg_defs/ska3-template/post-link.sh
Use sed to rewrite templates with the prefix of our installation.
This replaces the technique in #28
> Add back use of sed for template rewrite

- ska_conda/pkg_defs/ska3-flight/meta.yaml
- ska_conda/pkg_defs/ska3-template/bin/ska_version
- ska_conda/pkg_defs/ska3-template/meta.yaml
The dog-fooding begins...
The `:`-separated version actually breaks the Ska.engarchive long test because `:` in the path is interpreted as a path separator.  So using colon was just not a good choice.  But more to the point, I realized that in practice `ska3-flight` has embedded in it the other package versions.  Unless you purposely do crazy things with forcing different metapackages, the version of `ska3-flight` plus the SHA1 of everything is fine.
This PR makes that short form the default, but does add a `--full` option to get the full list consistent (mostly, see next paragraph) with the current output.
The other thing this changes is having *all* packages factor into the SHA hash.  This was mostly driven by having a simple code base that produces the same SHA for both the short and …
> Make ska_version output shorter by default

- ska_conda/pkg_defs/astropy/meta.yaml
- ska_conda/pkg_defs/astropy/old_gcc_cfitsio_patch.txt
- ska_conda/pkg_defs/ska3-core/README
- ska_conda/pkg_defs/ska3-core/meta.yaml
- ska_conda/pkg_defs/ska3-flight/meta.yaml
Update ska3-core to include modifications needed for 32bit linux. 
Also add a small patch for astropy when compiled on ancient 32 bit build system (the conda gcc didn't work either).
> Mods for 32 bit Linux

- ska_conda/pkg_defs/acis_taco/meta.yaml
Remove "noarch: python" from acis_taco recipe so it becomes a regular arch package.
It looks like this is the easiest way to let the current acis_taco install make_esaview_data.py (which it is set to do from setup.py). It also puts the task_sched* files in prefix/share/acis_taco.
Closes #57
> Make acis_taco an arch package

- pkg_defs/ska3-flight/meta.yaml
- pkg_defs/ska3-template/build.sh
- pkg_defs/ska3-template/meta.yaml
Update ska3-template to actually install 'skare'
This is a trivial update to actually install the 'skare' script that was already in the ska3-template bin directory.  The 'sed' part of the build process will be a no-op on the 'skare' script itself, but that is not a an issue.
> Update ska3-template to actually install 'skare'

- pkg_defs/ska3-flight/meta.yaml
This includes changes to cmd_states and kadi to support that WSVIDALLDN sets ccd_count to 0.
There's also a new version of acis_thermal_check that uses the sqlite database by default instead of Sybase.
> ACIS updates approved 31-Aug-2018

- pkg_defs/hopper/meta.yaml
- pkg_defs/jplephem/meta.yaml
- pkg_defs/proseco/build.sh
- pkg_defs/proseco/meta.yaml
- pkg_defs/ska3-flight/meta.yaml
- pkg_defs/ska3-perl/meta.yaml
- pkg_defs/starcheck/build.sh
- pkg_defs/starcheck/meta.yaml
- ska3_flight_build_order.txt
- ska_builder.py
Updates to chandra_aca, agasc, xija
Inclusion of starcheck and a more rigorous ska3-perl metapackage.
- [Infrastructure improvements to transform module](https://github.com/sot/chandra_aca/pull/66)
- [Add new grid model infrastructure and 2018-11 acq prob model](https://github.com/sot/chandra_aca/pull/65)
- [Include near neighbor stars and exclude rarely used cols from miniagasc](https://github.com/sot/agasc/pull/36)
- [Update COLOR1 column to reflect AGASC 1.7 mag updates](https://github.com/sot/agasc/pull/37)
- Release 4.13 with step function power input from xija 3.12 (already in Ska2) and new Qt gui_fit now in 4.13
- [Remove unused 'check' blocks in cmds task_schedules](https://github.com/sot/kadi/pull/121)
- [Do event updates on a local copy and move …
> Collection of updates for starcheck + chandra_aca + agasc 

- pkg_defs/ska3-matlab/meta.yaml
- ska3_flight_build_order.txt
Make a ska3-matlab metapackage.  This starts from ska3-flight 2018.12.18 plus some anticipated bugfixes.
> Make ska3-matlab metapackage

- pkg_defs/aca_preview/build.sh
- pkg_defs/aca_preview/meta.yaml
- ska3_flight_build_order.txt
Add aca_preview package for building
> Add aca_preview package for building

- pkg_defs/ska3-core/meta.yaml
Fix preprocessing selector logic bugs
All of the "and" statements were wrong as when building a platform cannot both be linux64 and osx.  I think this was just not noticed as most of these explicit package includes get pulled in by other packages.  The incorrect boolean logic resulted in the lines just being silently dropped when the linux64 and osx metapackages were built.
Closes #111
> Fix preprocessing selector logic bugs in ska3-core

- pkg_defs/ska3-matlab/meta.yaml
Updates for Feb 2019 Matlab release.  Updates include
1. proseco 4.4.1
2. aca_preview 4.0 -> sparkles 4.1.2
3. chandra_aca 4.25.2
4. mica 3.16
5. pyyaks 3.3.5 (included in previous update list for the unreleased MATLAB tools)
6. kadi 3.16.4
> Updates for Feb 2019 MATLAB release (the second one)

- pkg_defs/astropy-healpix/meta.yaml
- pkg_defs/astropy-healpix/run_test.py
- ska3_flight_build_order.txt
As noted in recipe comment, this recipe largely borrowed from
https://github.com/conda-forge/astropy-healpix-feedstock
but the build and run requirements have been set manually to ska3 requirements.
> Add astropy-healpix recipe

- pkg_defs/ska3-flight/meta.yaml
ska3-flight update for Matlab 2019_158
This includes xija 4.14, astropy-healpix, and proseco 4.5 .
> ska3-flight update for Matlab 2019_158

- pkg_defs/ska3-matlab/meta.yaml
Update xija to 4.14 in ska3-matlab
This includes the ska3-core update to install astropy-healpix.
> Update xija to 4.14 in ska3-matlab

- pkg_defs/ska3-flight/meta.yaml
Update mica to 3.18 to support acdc dark cals without error
Closes #144
> Update mica to 3.18

- pkg_defs/ska3-core/meta.yaml
Add conda itself (at version 4.3.21) to ska3-core
> Add conda itself (at version 4.3.21) to ska3-core

- pkg_defs/ska3-core/meta.yaml
Remove conda from ska3-core
It doesn't work to have it in ska3-flight in non-root environments
Closes #159
> Remove conda from ska3-core

- pkg_defs/mica/meta.yaml
- pkg_defs/ska3-flight/meta.yaml
Update mica to 4.18
Closes #150
> Update mica to 4.18

- pkg_defs/ska3-core/meta.yaml
This package is mostly just annoying as it makes it easy to lose the jupyter top menu bar in favor of the bottom nbpresent bar that we never use.
Closes #90
> Remove nbpresent from ska3-core

- pkg_defs/mica/meta.yaml
- pkg_defs/sparkles/meta.yaml
- pkg_defs/xija/meta.yaml
Update recipes to allow some ska packages to use more modern numpy
It would be great if we can make these recipes successfully build on CentOS5 but make packages that have requirements such that they can work on CentOS7 and OSX in a ska3-dev environment with more modern numpy (for testing and dev work).
There are still other packages that have numpy 1.12 hardcoded requirements (astropy, jplephem) but my hope would be that we could use those packages from a more modern repo from continuum in the more modern environment, instead of needing to build them in skare3.
> Update recipes to allow some ska packages to use more modern numpy

- pkg_defs/ska3-flight/meta.yaml
Updates for ska3-flight for week of 2019.08.19
Includes xija 4.15 and dea_check v2.3.0 .
Closes #190
> Updates for ska3-flight for week of 2019.08.19

- ska_builder.py
Set default numpy version when building to 1.12
This fixes an issue I had with package building where the solver would try to build with numpy 1.11 and then have conflicts with the requirements in our environment to use 1.12.
It should still make packages that can be used in environments with more modern numpy as needed.
> Set default numpy version when building to 1.12

- pkg_defs/ska3-flight/meta.yaml
I recommend not installing kadi 4.18 into flight (the only change for Weekly release 2019.09.17) at this time and waiting to cut a kadi release with real code changes of some kind.  As such, this PR reverts the ska3-flight update for kadi 4.18.
Reverts sot/skare3#203
> Revert "Weekly release 2019.09.17"

- pkg_defs/ska3-flight/meta.yaml
- pkg_defs/ska3-perl/meta.yaml
- pkg_defs/starcheck/meta.yaml
- ska3_flight_build_order.txt
Remove some starcheck dependencies from recipe
This should allow the starcheck conda package to build successfully and without the Perl dependencies.  Installing that package should make starcheck.parser available for proseco and annie without requiring a working starcheck/Perl environment.
Closes https://github.com/sot/mica/issues/204
> Move starcheck pkg into ska3-flight

- pkg_defs/acisfp_check/build.sh
Defined SKA=/proj/sot/ska and this worked in the build environment. Otherwise, the error was "no local Ska data found and remote access is not selected"
> fixed acisfp_check build.sh.

- .gitignore
- pkg_defs/Chandra.Time/build.sh
- pkg_defs/Chandra.Time/meta.yaml
- pkg_defs/Ska.Numpy/build.sh
- pkg_defs/Ska.Numpy/meta.yaml
- pkg_defs/Ska.Shell/build.sh
- pkg_defs/Ska.Shell/meta.yaml
- pkg_defs/Ska.engarchive/meta.yaml
- pkg_defs/acdc/meta.yaml
- pkg_defs/mica/meta.yaml
- pkg_defs/ska3-win/meta.yaml
- pkg_defs/xija/build.sh
- pkg_defs/xija/meta.yaml
- ska_builder.py
This is a proof-of-concept for making Windows builds which seems to be working.  I had quite a journey getting this working so ended up doing micro-commits to allow backtracking to a configuration that works.
It seems that using `python setup.py install` in this context is fine since conda is doing the file management and so `pip` is a bit of overkill.  But perhaps more importantly, modern `pip` has dropped support for eggs and this is needed for namespace packages.  So going to `python setup.py install` should allow upgrading `pip` to the latest.
It also seems like we can just use the `build : script` directive in `meta.yaml`, but maybe there is a reason not to that @jeanconn has discovered.
Next steps would be doing the rest of the arch-specific packages and then dealing with the core …
> WIP windows conda build for ska3-win

- pkg_defs/Chandra.Maneuver/meta.yaml
- pkg_defs/Ska.Shell/meta.yaml
- pkg_defs/acis_thermal_check/build.sh
- pkg_defs/acis_thermal_check/meta.yaml
- pkg_defs/acisfp_check/meta.yaml
- pkg_defs/agasc/meta.yaml
- pkg_defs/backstop_history/meta.yaml
- pkg_defs/dea_check/build.sh
- pkg_defs/dea_check/meta.yaml
- pkg_defs/dpa_check/meta.yaml
- pkg_defs/find_attitude/build.sh
- pkg_defs/find_attitude/meta.yaml
- pkg_defs/kadi/meta.yaml
- pkg_defs/mica/meta.yaml
- pkg_defs/psmc_check/build.sh
- pkg_defs/psmc_check/meta.yaml
- pkg_defs/ska3-core/meta.yaml
- pkg_defs/ska3-flight/meta.yaml
- pkg_defs/ska3-perl/meta.yaml
- pkg_defs/ska3_builder/meta.yaml
- pkg_defs/ska_sync/meta.yaml
- pkg_defs/sparkles/meta.yaml
The 2020.1 skare3 release is significant in that it includes substantive changes to a few packages and includes setuptools_scm modernization of most of our Python modules.
**[acis_taco](https://github.com/sot/acis_taco/releases/tag/4.1.0)**
- This code was used to make the xija file in flight use, but an updated acis_taco was not installed at that time
**[agasc](https://github.com/sot/agasc/releases/tag/4.8.0)**
**[annie](https://github.com/sot/annie/releases/tag/0.9.1)**
**[Chandra.Maneuver](https://github.com/sot/Chandra.Maneuver/releases/tag/3.7.2)**
**[Chandra.Time](https://github.com/sot/Chandra.Time/releases/tag/3.20.4)**
**[find_attitude](https://github.com/sot/find_attitude/releases/tag/3.3.2)**
- Mostly just a change in a module name.  Django 3.0 requires web apps to have a …
> Release 2020.1

- pkg_defs/ska3-matlab/meta.yaml
Includes these pkg updates
- acisfp_check v2.7.0
- acis_thermal_check v2.9.0
- chandra_aca 4.27
- chandra.cmd_states 3.15
- dea_check v2.3.0
- dpa_check v2.4.0
- kadi 4.18.1
- mica 4.19
- parse_cm 3.5
- proseco 4.7.1
- pyyaks 4.4
- ska.dbi 4.0
- ska.engarchive 4.47.3
- ska.ftp 3.5.1
- ska.shell 3.3.4
- ska_sync 4.5
- testr 4.3
adds pkgs
- setuptools_scm (added in ska3-core update which is not visible in the diff)
- acdc 4.3.1
- starcheck 13.5
- annie 0.8.2
> Update ska3-matlab in bulk for 2019_210

- ska_builder.py
Some of the red in the dashboard comes from this.
Automated build uses only basic authentication over https. I did not include ssh keys for the build process. For this reason, I would replace all uses of git@github.com: for the https url.
There are other possible solutions, I just chose the simplest one:
- add ssh keys
- make it an option of the script.
> git clone with https instead of ssh

- pkg_defs/ska3-flight/meta.yaml
**Quaternion**
Minor version increase. Interface changes backward compatible.
- sot/Quaternion/issues/5 New vectorized interface: allows handling of arrays of quaternions without using for loops.
- sot/Quaternion/issues/22 Implementation of setuptools_scm, to provide better handling of package versions.
- sot/Quaternion/issues/25 Setting up automated build of conda packages.
- sot/Quaternion/issues/16 Improving documentation.
**Kadi 5.0.1:**
patch version increase
- sot/Kadi/issues/157 Setting up automated builds.
- sot/Kadi/issues/156 Implementation of setuptools_scm.
- sot/Kadi/issues/154 Alerts to aca@head and remove OCC task_schedule configs.
**ACIS packages**
(patch version increases: acisfp_check 2.7.2, acis_thermal_check 2.9.2, backstop_history 1.1.2, dea_check 2.3.2, dpa_check …
> Release 2020.2

- pkg_defs/aca_view/build.sh
- pkg_defs/aca_view/meta.yaml
- pkg_defs/aca_view/run_test.py
This PR does not add aca_view to ska3-flight. I think that is ok. One can still do `conda install aca_view`. Would you prefer to add it to ska3-flight?
> Add aca view to skare3

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/general-issue.md
- .github/ISSUE_TEMPLATE/package-update.md
- .github/ISSUE_TEMPLATE/release.md
Issue templates. The one that motivated me to do this is the release template.
> Create issue templates

- pkg_defs/ska3-core/meta.yaml
- pkg_defs/ska3-flight/meta.yaml
- pkg_defs/ska3-matlab/meta.yaml
Release 2020.5 includes two package updates to ska3-flight and "catches up" ska3-matlab to ska3-flight.  As the package set described by ska3-matlab and ska3-flight for this release is the same, this has been tested and reviewed as single release candidate.  Changes summarized and described below for the two environments.
The ska3-flight 2020 release includes:
* a small bugfix to proseco required to correctly calculate and use acquisition probabilities in starcheck   
* a small update to the mica package to fix issues in its cron jobs related to the Python 3 migration
* None
* Release passes Python Ska3 functional and integration testing.
* All PRs reviewed by ACA team.
* The 2020.5 ska3-flight release will be deployed on HEAD and GRETA ska3/flight after the release and products for the …
> Release 2020.5

- pkg_defs/ska3-flight/meta.yaml
The ska3-flight 2020.6 release includes:
* starcheck updates to
* work better with the April ACA CCD limit increase
* support RLTT and schedule stop
* kadi commands-related updates to
* support the starcheck RLTT and schedule stop change
* add support for ACIS FP state
* eng_archive update to support computed msids
* Ska and Chandra are now "native namespace packages". This is a purely technical change that makes maintenance easier. 
* Documentation for acis_thermal_check
* None
* Standard suite of regression tests was run on HEAD (summary below)
* One Ska.engarchive test fails. This test was reported failing in the previous release, so here we note again: this test failure is a known and non-impacting issue with the sync process / sync test.
* PRs (see changes below) have been reviewed …
> Release 2020.6

- pkg_defs/ska3-core-latest/meta.yaml
- ska3_flight_arch_specific.txt
- ska_builder.py
This is a few commits that I have been using locally for shiny work.
- Allow specifying --tag when building list of packages
- Add astropy-sphinx-theme
- Pull from tag before building (this one might break if you supply a commit hash as the tag, need to check).
About pulling from the tag, the current version just fetches and then checks out at the tag, but this can leave the local repo behind unless you also pull. At least that is what happened to me trying to build Chandra.Time on the `shiny` branch.
> WIP: shiny improvements

- pkg_defs/task_schedule/build.sh
- pkg_defs/watch_cron_logs/build.sh
Update recipes to make bin dir
These simple builds don't work with modern conda without this change.
> Update recipes to make bin dir

- pkg_defs/Chandra.Maneuver/meta.yaml
- pkg_defs/backstop_history/meta.yaml
- pkg_defs/ska3-core-latest/meta.yaml
- ska_builder.py
This is a WIP for making `ska_builder.py` a bit more organized, simpler and modern.
A key functional change is defaulting to just using the packages in `pkg_defs`, agreeing now with the suggestion from @javierggt.  Having looked more carefully at the diffs from what is there vs. the build order file, basically we either want to just build the packages (like the new ACIS checkers) or remove the recipe (like jplephem).
It also now allows specifying one or more packages to build by name.
Also removes the caching of git repos entirely in order to make the code simpler and more reliable.  From my experience the time for cloning is a small part of the overall build time.
> WIP: refactor, modernize, improve ska_builder.py

- pkg_defs/skare3_tools/build.sh
- pkg_defs/skare3_tools/meta.yaml
This recipe ends up pulling several packages that are not currently in our repository. That is thanks to these three dependencies:
- google-auth-oauthlib
- google-api-python-client
- sphinx-argparse
The last one is just for documentation (useful for documenting scripts).
Where this goes is an open question. At least I wanted to have it somewhere documented.
> Add conda recipe for skare3 tools

- pkg_defs/Chandra.Time/meta.yaml
- pkg_defs/Ska.Numpy/meta.yaml
- pkg_defs/xija/meta.yaml
Use the anaconda compilers on osx and linux
My understanding is that the anaconda clang on OSX will need access to an SDK and is configured by default to use /opt/MacOSX10.9.sdk.  I haven't figured out how to use a different one or how to get it to respect MACOSX_DEPLOYMENT_TARGET and CONDA_BUILD_SYSROOT . 
It also looks to me like if /opt/MacOSX10.9.sdk isn't present but there is an SDK installed in /Library from Xcode, the anaconda clang seems to work with that without error.
> Use the anaconda compilers on osx and linux

- pkg_defs/ska3-flight/meta.yaml
The ska3-flight 2020.6 release includes:
* Update dea_check to 3.1.0
* None
* Standard suite of regression tests was run on HEAD (summary below)
* One Ska.engarchive test fails. This test was reported failing in the previous release, so here we note again: this test failure is a known and non-impacting issue with the sync process / sync test.
```
**************************************************************
***      Package                  Script            Status ***
*** ------------------ ---------------------------- ------ ***
***   Chandra.Maneuver                 test_unit.py   pass ***
***   Chandra.Maneuver           post_check_logs.py   pass ***
***       Chandra.Time                 test_unit.py   pass ***
***       Chandra.Time           post_check_logs.py   pass ***
*** …
```
> Release 2020.7 , update dea_check to 3.1.0

- ska_builder.py
Shiny is now targeting Python 3.8.
> Update default Python version to 3.8

- ska_builder.py
Allow there to be text like `{{ compiler('c') }}` in the `meta.yaml` file.
- [N/A] Unit tests
Used this patch to build `sherpa` which contains:
```
requirements:
build:
- {{ compiler('cxx') }}
- {{ compiler('c') }}
- make
- bison
- flex
```
Doing the build includes this output, which seems to indicate using local compilers:
```
+CLANG=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-clang
+CMAKE_PREFIX_PATH=:$PREFIX
+INDR=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-indr
+INSTALL_NAME_TOOL=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-install_name_tool
+LD=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-ld
...
+CLANGXX=$BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-clang++
+CXX=x86_64-apple-darwin13.4.0-clang++
```
Fixes #391
> Allow for meta.yaml compiler option in ska_builder

- pkg_defs/sherpa/build.sh
- pkg_defs/sherpa/meta.yaml
- pkg_defs/sherpa/multiprocess_patch.txt
Add a recipe for building sherpa.  This is intended to be temporary and to be removed once an official conda package for Sherpa is available for Python 3.8 on linux and Mac.  The recipe was adapted with minimal modification from the recipe included in the sherpa source.
Used `python ska_builder.py --python=3.8 sherpa` to successfully build `sherpa` 4.12.1.  This package was installed and passed `sherpa_test`.  I also ran `xija_gui_fit` using this and was able to successfully run a simple fit without any crash.
> Add recipe for sherpa

- pkg_defs/Ska.engarchive/meta.yaml
- pkg_defs/aca_view/build.sh
- pkg_defs/aca_view/meta.yaml
- pkg_defs/acdc/meta.yaml
- pkg_defs/kadi/meta.yaml
- pkg_defs/sherpa/meta.yaml
- pkg_defs/ska_sync/meta.yaml
- pkg_defs/sparkles/meta.yaml
- pkg_defs/testr/meta.yaml
- ska_builder.py
This makes some improvements related to arch-specific packages:
- Allow only building them (convenient on linux and Windows, assuming noarch packages are built on Mac)
- Make every package with entry point scripts be arch-specific
- Make sherpa build be skipped on Windows
> Improvements related to arch-specific packages

- fix_repodata.py
- upload_packages.py
This removes the hack of post-facto fix of `repodata.json` (and co.) in favor of actually opening the `.conda` zip archives, fixing the dependencies, and then reconstituting the whole thing.
Along the way I learned about libarchive, which is used by conda build.  It is horribly documented but does provide a convenient multi-platform way to deal with archives.  In particular the .conda package has zstandard-compressed tar files, which are difficult to handle on Windows without this.
With this new capability then `fix_repodata.py` will go away.
> Fix conda package dependencies directly in package

- pkg_defs/acispy/meta.yaml
The run requirements come from the setup.py. This is done as arch-specific because of the script files.
> Add a recipe for the ACISpy package

- pkg_defs/ska3-flight/meta.yaml
- pkg_defs/ska3-matlab/meta.yaml
The ska3-matlab 2020.8 release includes the latest  xija release 4.19.0. 
**sot/xija**: 4.18.1 -> 4.19.0 (4.18.1 -> 4.19.0)
- PR #90: Enhance StepFunctionPower component to allow multiple instances
- PR #86: Fix bug in component param set attribute
The test failures are the same as in the previous ska3-matlab release, which were considered acceptable:
* Ska.engarchive test failure is a known and non-impacting issue with the sync process / sync test.
* Ska.quatutil failure is due to a know and non-impacting test defect.
* maude failure is due to an acceptable regression caused by the recent MAUDE data updates
test_spec_SKA3_HEAD on kady
```
**************************************************************
***      Package                  Script            Status ***
*** ------------------ …
```
> ska3-matlab 2020.8

- pkg_defs/skare3_tools/meta.yaml
even if we are not explicitly supporting windows, this package defines entrypoints, so to even hava a chance needs to be arch-dependent
> skare3_tools arch

- pkg_defs/cxotime/meta.yaml
adding more build dependencies to cxotime (until it builds in CI: https://github.com/sot/cxotime/runs/1220403139)
> adding gcc build dependency to cxotime (until it builds in CI)

- pkg_defs/cxotime/meta.yaml
I tested that this produces an arch-dependent package on mac os.
> cxotime is not noarch anymore

- pkg_defs/ska3-core/combine_arch.py
- pkg_defs/ska3-perl/meta.yaml
Make a ska3-perl versioned metapackage for the shiny release candidate.  
Update combine_arch helper/utility script to with an option to subtract off the packages described by another platform-specific json file.  This new option was used to make the ska3-perl metapackage as the ska3-perl package should basically be the difference between the environment defined by (ska3-core ska3-flight ska3-perl-latest) and the one defined by (ska3-core ska3-flight).
> ska3-perl for shiny release candidate

- pkg_defs/ska3-core-latest/meta.yaml
This pulls in the following:
- sphinx-argparse-0.2
- commonmark-0.9.1
- future-0.18.2 
Fixes #513
> add sphinx-argparse

- ska_builder.py
This PR adds a command argument `--skare3-overwrite-version` which is meant for continuous integration to create pre-release conda packages.
It does that by:
- adding the `--skare3-overwrite-version` argument
- parsing the value provided
- the value can be of the form `<initial-version>:<final-version>`.
- or just a single version, in which case it assumes that the the initial version is the same os the final version but removing the release candidate part (i.e.: something that looks like "rcN" or "aN" or "bN".
- the package definition directory is copied to the temp source directory
- meta.yaml is read, all occurrences of `<initial-version>` are replaced by `<final-version>`. This is in the package version and in its dependencies, whenever their name is of the form 'ska3-*'.
built the …
> add option to overwrite ska3-* meta-package versions

- pkg_defs/Chandra.Maneuver/meta.yaml
- pkg_defs/acdc/meta.yaml
- pkg_defs/annie/meta.yaml
- pkg_defs/maude/meta.yaml
- pkg_defs/parse_cm/meta.yaml
- In all cases where home was a github repository, changed it to the corresponding https address.
I thought of also defining the doc_url and summary  fields (like I did with [skare3_tools](https://github.com/sot/skare3/blob/master/pkg_defs/skare3_tools/meta.yaml#L37)). Anyway the doc address will change after we overhaul the documentation. Still, I could do it...
> Changed some meta-data

- pkg_defs/ska-sphinx-theme/meta.yaml
Currently, if one wants to build the documentation, one installs the theme with 
```
pip install git+https://github.com/sot/ska-sphinx-theme.git
```
This PR adds a recipe for a conda package to skare3, in case people are interested.
> add ska-sphinx-theme

- pkg_defs/ska3-core-latest/meta.yaml
These two packages should be capture as core dependencies.  `tqdm` is currently coming in as a derived dependency, so this makes it a primary one given direct use in Ska packages now.
> Add plotly and tqdm to ska3-core-latest

- pkg_defs/Chandra.Time/meta.yaml
- pkg_defs/Ska.Numpy/meta.yaml
- pkg_defs/xija/meta.yaml
This PR changes the recipe for the xija package. It fixes the current build issue by building the package in python 3.8.10 and also fixing the versions of other build dependencies.
I verified that this:
To build from this branch using the current docker builder image:
```
docker run --rm  --name builder -v $GITHUB_WORKSPACE:/github/workspace -w /github/workspace \
>     -e CONDA_PASSWORD -e GIT_USERNAME -e GIT_PASSWORD \
>     docker.pkg.github.com/sot/skare3/centos7-builder:latest \
>     sot/xija --skare3-branch linux-build --force --tag 4.23.0
```
Fixes #674
> Xija linux build

- combine_arch_meta.py
- patch_instructions.py
- pkg_defs/ska3-core-latest/install_from_scratch.py
- pkg_defs/ska3-flight-latest/install_from_scratch.py
This PR adds scripts to update metapackages for the three platforms. They were used to produce release 2022.2.
This particular branch is an interactive rebase of the ska3-next branch. The scripts *should* work (they should be the same), but I have not tested them because an issue appeared with windows runners. I don't think I should spend more time with this and I'd rather push them to master for future reference.
> Ska3 next scripts

- pkg_defs/ska3-template/bin/ska_version
This is a trivial case. Up to now, "ska3-flight" is included in the version string if it is installed. This PR just adds ska3-matlab too.
Fixes #143
> Include ska3-matlab in output of ska_version when appropriate

- pkg_defs/Chandra.Maneuver/meta.yaml
- pkg_defs/Chandra.Time/meta.yaml
- pkg_defs/Chandra.cmd_states/meta.yaml
- pkg_defs/Ska.DBI/meta.yaml
- pkg_defs/Ska.File/meta.yaml
- pkg_defs/Ska.Matplotlib/meta.yaml
- pkg_defs/Ska.Numpy/meta.yaml
- pkg_defs/Ska.ParseCM/meta.yaml
- pkg_defs/Ska.Shell/meta.yaml
- pkg_defs/Ska.Sun/meta.yaml
- pkg_defs/Ska.arc5gl/meta.yaml
- pkg_defs/Ska.astro/meta.yaml
- pkg_defs/Ska.engarchive/meta.yaml
- pkg_defs/Ska.ftp/meta.yaml
- pkg_defs/Ska.quatutil/meta.yaml
- pkg_defs/Ska.report_ranges/meta.yaml
- pkg_defs/Ska.tdb/meta.yaml
These changes will be needed in all current namespace packages if they are modified like in https://github.com/sot/Ska.Sun/pull/22
I noticed that many packages include this in their `setup.py`:
```python
try:
from testr.setup_helper import cmdclass
except ImportError:
cmdclass = {}
```
Up to now, this is never used, because testr is not a build dependency. This PR does not change that.
> add ska_helpers to build recipes

- .git_archival.txt
- .gitattributes
Since we are adding files to a package template, we might also add these, which are used for SCM versions.
> add files for scm version

- pkg_defs/chandra_time/meta.yaml
It seems we missed this one, so the build fails.
> Add testr to chandra_time build dependencies

- pkg_defs/chandra_cmd_states/meta.yaml
- pkg_defs/chandra_maneuver/meta.yaml
- pkg_defs/ska_dbi/meta.yaml
- pkg_defs/ska_ftp/meta.yaml
- pkg_defs/ska_numpy/meta.yaml
- pkg_defs/ska_quatutil/meta.yaml
- pkg_defs/ska_shell/meta.yaml
- pkg_defs/ska_tdb/meta.yaml
This PR adds a missing testr build dependency to some recipes.
We don't run test as part of the conda build process, but these packages now import testr in their setup.py files and need the package in the build environment to build successfully. 
testr itself is only used (after import) in these packages when running their tests.
> add missing testr to some build recipe dependencies

- ska_builder.py
Update default ska_builder python to 3.10 and numpy to 1.21
I think this is only used when building manually.
> Update default ska_builder python and numpy versions

- pkg_defs/chandra_limits/meta.yaml
Add simple meta/recipe for chandra_limits.  
I figured this could be tested with https://github.com/sot/chandra_limits/pull/1 , though I have not done so.  And https://github.com/sot/chandra_limits/pull/1 would still need the workflows for the actions for this to do something on merge.
> Add simple meta/recipe for chandra_limits

- environment-non-fsds.yml
Remove acis_taco from non-fsds package list
Our plan is to manage this non-fsds package list from master so this doesn't necessarily need to be in 2023.7 .
> Remove acis_taco from non-fsds package list

- templates/pyproject.toml
This might be controversial, but I often see many code warnings from pylance that come from half-baked notebooks that I'm working on within a code repo. These warnings obscure real warnings from production code. This update to `pyproject.toml` fixes that so that pylance warnings never appear for ipynb notebooks.
Annoyingly, there is a VS code setting that *should* work, but it doesn't:
This might stem from the odd difference between `exclude` and `ignore` in pyright (which is called by pylance):
https://github.com/microsoft/pyright/blob/main/docs/configuration.md#main-configuration-options
I used this in the `agasc` repo and VS code stopped showing warnings from a notebook in my editor.
> Update pyproject.toml to configure pylance behavior in VS code

- templates/ruff.toml
There are some deprecation warnings showing up in CI now that are related to breaking changes in [ruff 0.2](https://github.com/astral-sh/ruff/blob/main/CHANGELOG.md#020). This fixes the issues.
Ran ruff locally in this repo using ruff 0.2.1. Confirmed that deprecation warnings appear without the update and they are gone after the update.
> Update ruff template for ruff >= 0.2

- pkg_defs/chandra_time/meta.yaml
- pkg_defs/ska_numpy/meta.yaml
- pkg_defs/xija/meta.yaml
Update compiled recipes to use compiler directive.
I confirmed that these updated recipes resulted in build packages on linux and on osx-arm64 .  I didn't not test the packages.
I did not test on windows.
These don't work to build osx-64 packages on m1-m3 macs. AFAIK the current recipes in master also don't allow for osx-64 builds from m1-m3 macs -- this update to use the compiler directive doesn't fix that lack of cross-compile support.
> Update compiled recipes to use compiler directive

- templates/ruff-base.toml
This is a trivial update to target Python 3.11 in ruff.
> Update ruff-base.toml for Python 3.11

- pkg_defs/kadi-apps/meta.yaml
Now that I am adding a kadi-apps executable, I need the package to be arch-dependent.
> Make kadi-apps build recipe arch-dependent

- pkg_defs/sherpa/build.sh
- pkg_defs/sherpa/conda_build_config.yaml
- pkg_defs/sherpa/meta.yaml
This adds a recipe for sherpa.
I did not use `ska_builder.py` to build the package. I just did
```
conda build --python 3.11 --output-folder /Users/aca/skare3/builds pkg_defs/sherpa
```
This is the recipe used to build the **current** package 4.15.1.
> add build recipe for sherpa

- .github/ISSUE_TEMPLATE/release_flight.md
- .github/PULL_REQUEST_TEMPLATE/ska3-flight.md
Remind about ska3-perl in PR template and Issue template .
> Remind about ska3-perl in PR template and Issue template

- templates/ruff-base.toml
Exclude PLR1730 in ruff-base.toml template file.
> Exclude PLR1730 in ruff-base

- templates/pyrightconfig.json
It turns out that adding a `pyrightconfig.json` file is a bad idea: https://github.com/microsoft/pylance-release/issues/6446
Basically adding even an empty `pyrightconfig.json` file ends up turning on type checking (it sets `python.analysis.TypeCheckingMode` to `standard`. Then simple code like this gets a warning:
```
x = {"b": "c"}
x["d"] = 1  # it thinks x is dict[str, str]
```
So we should remove this config file from our repos and individual users will need to configure VS code:
```
"python.analysis.ignore": [
"**/*.ipynb"
],
```
I think the other `ignore` values are not really needed in practice, but pylance really doesn't deal well with notebooks.
> Remove pyrightconfig.json file from templates

- environment-non-fsds.yml
- pkg_defs/acq_stat_reports/meta.yaml
- pkg_defs/guide_stat_reports/meta.yaml
This PR add recipes for acq_stat_reports  and guide_stat_reports.
I Verified that these build locally and that they installed the scripts:
```
./ska_builder.py acq_stat_reports --tag master
./ska_builder.py guide_stat_reports --tag v3
conda install -c file://`pwd`/builds acq_stat_reports
conda install -c file://`pwd`/builds -y guide_stat_reports
mamba install -c flight -y ska_report_ranges
mamba update -c masters chandra_aca
acq-stat-reports -h
acq-stat-reports-summary -h
acq-stat-reports-toc -h
guide-stat-reports -h
guide-stat-reports-summary -h
guide-stat-reports-toc -h
```
> add recipes for acq_stat_reports  and guide_stat_reports

- templates/ruff-base.toml
See https://docs.astral.sh/ruff/rules/assert/ and https://github.com/sot/chandra_aca/pull/174/files#r1795584783.
> Update ruff-base.toml to discourage using assert in code except for tests

- pkg_defs/fotmp/meta.yaml
Add recipe for fotmp package.
I tested this locally with 
```
python ska_builder.py fotmp --tag 614d40b --override-channels -c https://icxc.cfa.harvard.edu/aspect/ska3-conda/flight -c conda-forge
```
and confirmed it made a package.
> Add recipe for fotmp package

- environment-non-fsds.yml
- pkg_defs/aperoll/meta.yaml
- pkg_defs/aperoll/run_test.py
This PR adds a recipe for aperoll and adds it to the non-fsds environment.
I used this branch to build the latest release of aperoll, installed it from the test conda channel, and it works as expected.
> add aperoll

- .github/ISSUE_TEMPLATE/release_flight.md
- .github/ISSUE_TEMPLATE/release_matlab.md
This PR adds one step to the release checklist. After `conda update` we have to remember to run `python -m compileall`
> release checklist step to compile all python code

- templates/ruff-base.toml
Python files hanging around in `build` should not be ruff formatted.
I tested this in `ska_trend` and confirmed that `build` was excluded as expected.
> Update ruff-base.toml to exclude "build" dir

- pkg_defs/ska3-core-latest/meta.yaml
Add configobj to ska3-core-latest
This package is already in ska3-core, but missing in ska3-core-latest.  However, there is a direct dependence in kadi so this should be in core latest too.
> Add configobj to ska3-core-latest

- pkg_defs/ska3-core-latest/meta.yaml
Add pydata-sphinx-theme and sphinx-copybutton to core-latest.
This supersedes #1481 as it was based on 2025.1-branch.
> Add pydata-sphinx-theme and sphinx-copybutton

- pkg_defs/aca_view/meta.yaml
- pkg_defs/cheta/meta.yaml
- pkg_defs/cxotime/meta.yaml
- pkg_defs/kadi/meta.yaml
- pkg_defs/skare3_tools/meta.yaml
- pkg_defs/sparkles/meta.yaml
- pkg_defs/testr/meta.yaml
- pkg_defs/xija/meta.yaml
This PR sets some entrypoints explicitly. This branch was already used to build the corresponding packages, and they are already in the test conda channel. They were used to test [ska3-matlab 2025.2rc1 on windows](https://icxc.cfa.harvard.edu/aspect/skare3/testr/releases/2025.2rc1-Windows/).
To merge this, I would actually remove the commit where I set the build number.
> Entrypoints

- ska_builder.py
Trivial change: Update default arguments in ska_builder.py to python 3.12 and numpy 1.26.4.
I just used this to test #1479
> Update default arguments in ska_builder.py

- .github/workflows/build_package.yml
- .github/workflows/package_build.yml
This PR avoids the error seen in recent builds, where there is an authorization error when accessing our private conda repo. I do not know the exact cause of the error, but I am guessing that somewhere the repo URL is interpreted so all special characters are escaped, and the password is not replaced.
This PR also removes conda-forge from the channels used during build. This is to avoid breaking the build when something is updated in conda-forge. It adds an option to use conda-forge, because sometimes it might be needed.
I tested this in the test-actions repo.
> add channels by hand after environment is setup

- templates/ruff-base.toml
Rule PLW1641 requires that any class that implements `__eq__` also implements `__hash__`. 
This is misguided since in practice it is common for classes to define a "liberal" view of equality where objects that compare equal do not have the same hash. As a simple example, `np.dtype("float64") == "float64"` is `True`, while the `hash()` values are not equal.
In our code base it is fine for a class object to not be hashable by default, which is what can happen by ignoring PLW1641.
> Update ruff-base.toml to ignore PLW1641
