- ska_conda/pkg_defs/ska3-template/bin/ska_version
Add a ska_version script that uses 'conda list'.
> Add a ska_version script that uses 'conda list'

- ska_conda/pkg_defs/ska3-core/meta.yaml
- ska_conda/pkg_defs/ska3-flight/meta.yaml
Update metapackages for recent changes
This brings ska3-flight a bit ahead of HEAD flight
> Update metapackages for recent changes

- ska_conda/build_order.txt
- ska_conda/pkg_defs/ipywidgets/meta.yaml
- ska_conda/pkg_defs/ska3-core/meta.yaml
- ska_conda/pkg_defs/ska3-flight/meta.yaml
- ska_conda/pkg_defs/widgetsnbextension/meta.yaml
- ska_conda/pkg_defs/widgetsnbextension/post-link.bat
- ska_conda/pkg_defs/widgetsnbextension/post-link.sh
- ska_conda/pkg_defs/widgetsnbextension/pre-unlink.bat
- ska_conda/pkg_defs/widgetsnbextension/pre-unlink.sh
- ska_conda/ska_builder.py
Make custom widgetsnbextension and ipywidgets
These recipes (like astropy) are borrowed from conda-forge.
> Make custom widgetsnbextension and ipywidgets

- ska_conda/pkg_defs/ska3-flight/meta.yaml
Update parse_cm to 3.4 in ska3-flight
> Update parse_cm to 3.4 in ska3-flight

- ska_conda/pkg_defs/ska3-dev/meta.yaml
- ska_conda/pkg_defs/ska3-flight/meta.yaml
- ska_conda/pkg_defs/ska_sync/build.sh
- ska_conda/pkg_defs/ska_sync/meta.yaml
> Add ska_sync

- ska_conda/build_order.txt
- ska_conda/pkg_defs/acis_taco/build.sh
- ska_conda/pkg_defs/acis_taco/meta.yaml
- ska_conda/pkg_defs/acis_thermal_check/build.sh
- ska_conda/pkg_defs/acis_thermal_check/meta.yaml
- ska_conda/pkg_defs/acis_thermal_check/run_test.py
- ska_conda/pkg_defs/acisfp_check/build.sh
- ska_conda/pkg_defs/acisfp_check/meta.yaml
- ska_conda/pkg_defs/acisfp_check/run_test.py
- ska_conda/pkg_defs/backstop_history/build.sh
- ska_conda/pkg_defs/backstop_history/meta.yaml
- ska_conda/pkg_defs/dea_check/build.sh
- ska_conda/pkg_defs/dea_check/meta.yaml
- ska_conda/pkg_defs/dpa_check/build.sh
- ska_conda/pkg_defs/dpa_check/meta.yaml
- ska_conda/pkg_defs/psmc_check/build.sh
- ska_conda/pkg_defs/psmc_check/meta.yaml
- ska_conda/pkg_defs/ska3-dev/meta.yaml
- ska_conda/pkg_defs/ska3-flight/meta.yaml
> Add acis checkers

- ska_conda/pkg_defs/ska3-flight/meta.yaml
> Update kadi to version 3.16

- ska_conda/pkg_defs/task_schedule/build.sh
- ska_conda/pkg_defs/task_schedule/meta.yaml
- ska_conda/pkg_defs/watch_cron_logs/build.sh
- ska_conda/pkg_defs/watch_cron_logs/meta.yaml
Add recipes for task_schedule and watch_cron_logs
> Cron runners

- pkg_defs/ska3-core/meta.yaml
- pkg_defs/ska3-dev/meta.yaml
- pkg_defs/ska3-flight/meta.yaml
Add lxml per mta request
This also adds the other dependencies as required: 
libiconv and libxml2 added to osx
libxslt and lxml added for both os
> Add lxml per mta request

- pkg_defs/ska3-flight/meta.yaml
> Update xija to 3.11.1

- pkg_defs/task_schedule/build.sh
- pkg_defs/watch_cron_logs/build.sh
Update cron runner recipes to just install by copying
> Update cron runner recipes to just install by copying

- pkg_defs/ska3-core/meta.yaml
- pkg_defs/ska3-flight/meta.yaml
> Add blas to ska3-core

- pkg_defs/jplephem/0001_use-setuptools.patch
- pkg_defs/jplephem/meta.yaml
Add jplephem recipe
This doesn't have a built conda package in defaults, so adding the recipe from conda-forge if we choose to add it to skare3.
> Add jplephem recipe

- pkg_defs/ska3-flight/meta.yaml
> Update proseco to 4.3

- pkg_defs/ska3-flight/meta.yaml
Update acis_taco to 4.0.1 in ska3-flight
> Update acis_taco to 4.0.1 in ska3-flight

- pkg_defs/ska3-perl/meta.yaml
Update starcheck to 13.0 in skare3 (via ska3-perl metapackage)
> Update starcheck to 13.0 in skare3 (via ska3-perl metapackage)

- pkg_defs/sparkles/build.sh
- pkg_defs/sparkles/meta.yaml
Fix sparkles recipe
Closes #116
> Fix sparkles recipe

- pkg_defs/ska3-flight/meta.yaml
Update acisfp_check to v2.5.0 in ska3-flight
> Update acisfp_check to v2.5.0 in ska3-flight

- pkg_defs/ska3-perl/meta.yaml
- pkg_defs/starcheck/meta.yaml
ska3-perl updates for Ska::Convert and starcheck 13.1
> ska3-perl updates for Ska::Convert and starcheck 13.1

- pkg_defs/ska3-flight/meta.yaml
Collection of updates for proseco 4.4.1 and starcheck 13.1
Closes #115 
Closes #98
> Collection of updates for proseco 4.4.1 and starcheck 13.1 (ska3-flight)

- pkg_defs/annie/build.sh
- pkg_defs/annie/meta.yaml
Update annie recipe for pinned llvmlite and non-set SKA
> Update annie recipe for pinned llvmlite and non-set SKA

- pkg_defs/aca_egse/build.sh
- pkg_defs/aca_egse/meta.yaml
> Add an aca_egse recipe

- pkg_defs/ska3-flight/meta.yaml
- pkg_defs/ska3-perl/meta.yaml
Misc ska3 updates for week of 08-Apr-2019
> Misc ska3 updates for week of 08-Apr-2019

- pkg_defs/xija/meta.yaml
Update recipe for xija with numba and pinned llvmlite
> Update recipe for xija with numba and pinned llvmlite

- pkg_defs/ska3-flight/meta.yaml
- pkg_defs/ska3-perl/meta.yaml
This includes chandra_aca 4.26 and starcheck 13.2 .
Closes #139 
Closes #138
> Updates for 2019.06.10 "weekly" release

- pkg_defs/ska3-core/meta.yaml
Add astropy-healpix to ska3-core
Closes #131
> Add astropy-healpix to ska3-core

- pkg_defs/ska3-flight/meta.yaml
ACIS updates approved 19-Jun-2019
> ACIS updates approved 19-Jun-2019

- pkg_defs/ska3-core/meta.yaml
Add setuptools_scm to ska3-core
Closes #140
> Add setuptools_scm to ska3-core

- pkg_defs/ska3-flight/meta.yaml
Add kadi 4.17 to ska3-flight
Closes #147
> Add kadi 4.17 to ska3-flight

- pkg_defs/ska3-flight/meta.yaml
Update parse_cm to 3.5 in ska3-flight
Closes #146
> Update parse_cm to 3.5 in ska3-flight

- pkg_defs/ska3-core/meta.yaml
- pkg_defs/ska3-flight/meta.yaml
Update ska3-core and ska3-flight versions for 2019.07.01 release
> Update ska3-core and ska3-flight versions for 2019.07.01 release

- pkg_defs/ska3-perl/meta.yaml
> Update starcheck to 13.3

- pkg_defs/ska3-core/meta.yaml
- pkg_defs/ska3-flight/meta.yaml
Update ska3-flight for weekly update 2019.07.22
> Update ska3-flight for weekly update 2019.07.22

- pkg_defs/ska3-flight/meta.yaml
> Update pyyaks to version 4.4

- pkg_defs/acdc/build.sh
- pkg_defs/acdc/meta.yaml
- pkg_defs/ska3-flight/meta.yaml
Add acdc at version 4.0
Closes #145
> Add acdc at version 4.2

- pkg_defs/ska3-core/meta.yaml
> Revert "Remove nbpresent from ska3-core"

- pkg_defs/ska3-flight/meta.yaml
Update ska3-flight for 2019.08.12
The changes merged to master that will become tagged with this release include
acdc 4.2
pyyaks 4.4
Closes #182
> Update ska3-flight for 2019.08.12

- pkg_defs/Ska.engarchive/meta.yaml
Found these dependencies trying a fresh install
> Add dependencies for ska.engarchive

- pkg_defs/ska3-template/bin/flt_envs
- pkg_defs/ska3-template/meta.yaml
Update flt_envs for Sybase 16.0
> Update flt_envs for Sybase 16.0

- pkg_defs/ska3-flight/meta.yaml
> Weekly release 2019.09.17

- pkg_defs/ska3-flight/meta.yaml
Weekly release 2019.09.30
- closes #178 
- closes #197 
- closes #202 
- closes #207
> 2019.09.30

- pkg_defs/ska3-matlab/meta.yaml
Ska/Python updates in support of Matlab 2019_205
> Ska/Python updates in support of Matlab 2019_205

- pkg_defs/ska3-flight/meta.yaml
Also bumped the version of ska3-flight.
> Update to version 2.7.0 of acisfp_check

- pkg_defs/ska3-flight/meta.yaml
Updates to ska3-flight for 2019.11.15
> Flight 2019.11.15

- pkg_defs/ska3-flight/meta.yaml
> dpa_check 2.5.0

- pkg_defs/ska3-flight/meta.yaml
> Update psmc_check to 1.3.0

- pkg_defs/bep_pcb_check/build.sh
- pkg_defs/bep_pcb_check/meta.yaml
- pkg_defs/fep1_actel_check/build.sh
- pkg_defs/fep1_actel_check/meta.yaml
- pkg_defs/fep1_mong_check/build.sh
- pkg_defs/fep1_mong_check/meta.yaml
Changes are still not finished.
> added new acis packages bep_pcb_check fep1_actel_check fep1_mong_check

- pkg_defs/Chandra.Time/meta.yaml
- pkg_defs/Ska.Numpy/meta.yaml
- pkg_defs/xija/meta.yaml
Add some more explicit dependencies.
I like these for more modular testing.  I'll collect more as I run into them.
> Dependency tweaks

- pkg_defs/ska3-core-latest/meta.yaml
- ska3_flight_arch_specific.txt
- ska_builder.py
- Allow specifying --tag with multiple packages and pull from tag before building
- Add astropy-sphinx theme
- Add list of arch-specific packages
> Shiny pull from tag

- ska_builder.py
This allows changing the org of a repo, e.g. from acisops to sot in the case of a forked repo.
This PR is conservative and removes the repo if you are playing around with the org to ensure that upstream and origin are always correct.  For the purpose of code simplicity it always makes a new remote `upstream` which is where tags come from, but `upstream` is usually the same as `origin`.
I also made it so that when `--force` is supplied that the cache files and cached package are removed. I've noticed some problem with the cache files being there and processing not happening like I expected. I never totally understood what was happening but eventually was doing this cache cleaning by hand when rebuilding the same package.
I ran this for `backstop_history` in the acisops org and successfully …
> Allow changing the org of a repo and improve --force

- upload_packages.py
This uploads all the packages in the current conda environment to the upstream repository where they can be indexed and used for creating user environments.
> Script to upload packages to upstream repository

- .github/workflows/build_prerelease.yml
- .github/workflows/build_release.yml
Github workflows: added regression test and repeated with release workflow
> Release workflow

- pkg_defs/ska3-flight-latest/meta.yaml
This was missing, but adding this should not be controversial.
> Add aca_view to shiny

- pkg_defs/prompt-toolkit/meta.yaml
This allows making a local build of 2.0.10 which fixes problems on Windows.
> Add recipe for prompt-toolkit

- pkg_defs/ska3-perl-latest/meta.yaml
The analogy to ska3-flight-latest and ska3-core-latest.
> Shiny ska3 perl latest

- pkg_defs/skare3_tools/meta.yaml
added skare3_tools missing build dependency
> added skare3_tools missing build dependency

- pkg_defs/skare3_tools/meta.yaml
since shiny, google drive will be deprecated, so I am removing the dependency from the build. Also adding some meta info.
> Skare3 tools meta update

- pkg_defs/aca_hi_bgd/meta.yaml
> Add a recipe for aca_hi_bgd

- pkg_defs/ska3-flight/meta.yaml
The ska3-flight 2020.11 includes an update to starcheck.
* None
* One or more schedules were run for each functional change.
* The full regression test set has been run, which largely shows the differences from the new thermal model.
*  The 2020.11 ska3-flight release will be deployed on HEAD and GRETA ska3/flight after the release and products for the week are approved.
**starcheck 13.6.0-> 13.7.0**
See https://github.com/sot/starcheck/releases/tag/13.7.0 for a description of the changes
ska_testr run
The failures in Ska.engarchive and kadi are expected and are present in flight
```
**************************************************************
***      Package                  Script            Status ***
*** ------------------ ---------------------------- ------ ***
*** …
```
> Release 2020.11

- pkg_defs/cxotime/meta.yaml
Fixes https://github.com/sot/cxotime/issues/19
> bugfix: added numpy to cxotime meta.yml.

- pkg_defs/Ska.report_ranges/meta.yaml
- pkg_defs/perigee_health_plots/meta.yaml
- pkg_defs/ska3-flight-latest/meta.yaml
- ska3_flight_build_order.txt
Add perigee_health_plots and Ska.report_ranges
> Add perigee_health_plots and Ska.report_ranges

- ska3_flight_build_order.txt
> Add aca_hi_bgd to build order

- ska3_flight_arch_specific.txt
Remove unused ska3_flight_arch_specific.txt
> Remove unused ska3_flight_arch_specific.txt

- pkg_defs/ska3-flight/meta.yaml
Update ACIS packages for backstop_history 1.2.0
> Update ACIS packages for backstop_history 1.2.0

- pkg_defs/aca_weekly_report/meta.yaml
- pkg_defs/ska3-flight-latest/meta.yaml
> Add aca_weekly_report

- pkg_defs/ska3-flight-latest/meta.yaml
Add perigee_health_plots to ska3-flight-latest
> Add perigee_health_plots to ska3-flight-latest

- pkg_defs/ska3-flight-latest/meta.yaml
Add aca_hi_bgd to ska3-flight-latest
> Add aca_hi_bgd to ska3-flight-latest

- pkg_defs/skare3_tools/meta.yaml
remove keyring from skare3_tools requirements
> remove keyring from skare3_tools requirements

- pkg_defs/ska3-flight/meta.yaml
- pkg_defs/ska3-matlab/meta.yaml
Updates to proseco and starcheck for ACA limit increase
Planning limit increase -7.1 C to -6.5 C, penalty limit -8.1 C to -7.5 C.
> Updates to proseco and starcheck for ACA limit increase

- pkg_defs/jobwatch/meta.yaml
- pkg_defs/ska3-flight-latest/meta.yaml
> Add jobwatch

- pkg_defs/fot-matlab/meta.yaml
- pkg_defs/fot_matlab/meta.yaml
Add fot_matlab Python package as a fot-matlab conda package.
> Add fot_matlab module

- .github/workflows/build_release.yml
Add env vars for HEAD Sybase mica test
> Add env vars for HEAD Sybase mica test

- pkg_defs/kadi-apps/meta.yaml
This PR adds a new package: kadi-apps. This packages is not intended to be part of ska3-flight/core.
> add kadi-apps

- pkg_defs/Chandra.Maneuver/meta.yaml
- pkg_defs/Chandra.cmd_states/meta.yaml
- pkg_defs/acdc/meta.yaml
- pkg_defs/acis_taco/meta.yaml
- pkg_defs/acis_thermal_check/meta.yaml
- pkg_defs/acisfp_check/meta.yaml
- pkg_defs/ska3-flight-latest/meta.yaml
- pkg_defs/ska_sun/meta.yaml
> Update Ska.Sun to ska_sun

- pkg_defs/acis_thermal_check/meta.yaml
- pkg_defs/kadi/meta.yaml
Remove more unused and deprecated dependencies from recipes
> Remove more unused and deprecated dependencies from recipes

- templates/.github/pull_request_template.md
Add standard pull request template to templates
> Add standard pull request template to templates

- pkg_defs/vv_trending/meta.yaml
> Add vv_trending recipe

- pkg_defs/fss_check/meta.yaml
> Add fss_check recipe

- pkg_defs/twiki-wg/meta.yaml
Add twiki-wg recipe .
I tested this by building the conda package at https://github.com/sot/twiki-wg/pull/24/commits/9b2122fa99ad809d45d6805488603263fd2e16c1 and installing into a test environment.
> Add twiki-wg recipe

- pkg_defs/attitude_error_mon/meta.yaml
Add attitude_error_mon recipe.
Tested in https://github.com/sot/attitude_error_mon/pull/16.
> Add attitude_error_mon recipe

- environment-non-fsds.yml
Add twiki-wg and attitude_error_mon and update channel.
> Add twiki-wg and attitude_error_mon and update channel

- environment-non-fsds.yml
- pkg_defs/ska_trend/meta.yaml
Add ska_trend package
Testing:
I build a conda package from the first_draft branch of ska_trend and it seems functional.
> Add ska_trend package

- templates/.pre-commit-config.yaml
This should have been in #1252
> correct ruff version in pre-commit config

- environment-non-fsds.yml
- pkg_defs/fid_drift_mon/meta.yaml
> Add fid_drift_mon recipe

- ska_builder.py
Update ska_builder defaults and set to work from repos with master or main.
> Update ska_builder defaults and set to work from repos with master or main

- pkg_defs/schedule_view3/meta.yaml
> Add recipe for schedule_view3

- pkg_defs/razl/meta.yaml
> Add a meta.yaml for razl

- environment-non-fsds.yml
Add schedule_view3 to non-fsds env list
> Add schedule_view3 to non-fsds env list

- environment-non-fsds.yml
- pkg_defs/obc_rate_noise_plots/meta.yaml
This adds a recipe to build obc_rate_noise_plots.
Functional testing was done for sot/obc_rate_noise_plots/pull/5
> Obc rate noise plots

- templates/.pre-commit-config.yaml
Update template pre-commit file
> Update template pre-commit file

- pkg_defs/kadi/meta.yaml
If we want to have to requirements in the recipe, here they are.
If you prefer a subset of the requirements, we can do that too.
> set kadi requirements

- environment-non-fsds.yml
Update non-fsds packages environment:
- remove guide stat reports
> Update non-fsds packages environment
